language: php
php:
  - 5.3
before_script:
  - mysql -e 'create database IF NOT EXISTS intraface_test;'
  - pear channel-discover pear.phpunit.de
  - pear channel-discover zend.googlecode.com/svn
  - pear channel-discover pear.swiftmailer.org
  - pear channel-discover pear.doctrine-project.org
  - pear channel-discover pear.pdepend.org
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.docblox-project.org
  - pear channel-discover pear.domain51.com
  - pear channel-discover public.intraface.dk
  - pear channel-discover pear.doctrine-project.org
  - pear channel-discover htmlpurifier.org
  - pear channel-discover pear.michelf.com
  - pear channel-discover pearhub.org
  - pear channel-discover pear.phing.info
  - pear channel-discover pear.symfony-project.com
  - pear install --force --alldeps pear_packagefilemanager
  - pear install phing/Phing
  - pear install --force domain51/Phing_d51PearPkg2Task
  - pear install --force --alldeps intrafacepublic/Phing_IlibPearDeployerTask 
  - pear install --force --alldeps pear/PHP_CodeSniffer 
  - php generate_package_xml.php make 1.0.0
  - pear package src/package.xml
  - sudo pear install --alldeps --force Intraface-1.0.0.tgz
  - sudo rm Intraface-1.0.0.tgz
  - phpenv rehash
script: phpunit --configuration tests/unit/phpunit.example.xml tests/unit/.
