language: php
php:
  - 5.3
before_script:
  - mysql -e 'create database IF NOT EXISTS intraface_test;'
  - pear config-set preferred_state alpha
  - pear channel-discover pear.phpunit.de
  - pear channel-discover zend.googlecode.com/svn
  - pear channel-discover pear.swiftmailer.org
  - pear channel-discover pear.doctrine-project.org
  - pear channel-discover pear.saltybeagle.com
  - pear channel-discover pear.pdepend.org
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.docblox-project.org
  - pear channel-discover pear.domain51.com
  - pear channel-discover public.intraface.dk
  - pear channel-discover htmlpurifier.org
  - pear channel-discover pear.michelf.com
  - pear channel-discover pearhub.org
  - pear channel-discover pear.phing.info
  - pear channel-discover pear.symfony-project.com
  - pear install --force --alldeps pear_packagefilemanager
  - pear install phing/Phing
  - pear install --force domain51/Phing_d51PearPkg2Task
  - pear install --force --alldeps intrafacepublic/Phing_IlibPearDeployerTask 
  - pear install --force --alldeps pear/PHP_CodeSniffer 
  - php generate_package_xml.php make 1.0.0
  - pear package src/package.xml
  - pear install intrafacepublic/Ilib_Error-1.0.1
  - pear install pear/Translation2-2.0.4
  - pear install pear/Validate-0.8.5
  - pear install pear/XML_RPC2-1.1.1
  - pear install intrafacepublic/Ilib_RandomKeyGenerator-0.3.1
  - pear install --force intrafacepublic/Ilib_DBQuery-0.1.10
  - pear install --force intrafacepublic/IntrafacePublic_Client_XMLRPC
  - pear install --force intrafacepublic/Ilib_Variable-1.0.1
  - sudo pear install --alldeps --force Intraface-1.0.0.tgz
  - sudo rm Intraface-1.0.0.tgz
  - php tests/unit/setup_database.php
  - pear install --force intrafacepublic/Ilib_Testing_Selenium_Selenese_TestSuiteGenerator-0.1.2
  - php tests/selenium/generate_test_suite.php
  - pear install phpunit/PHPUnit_Selenium
  - python -m SimpleHTTPServer 8080 > /dev/null 2>&1 &
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.22.0.jar
  - java -jar selenium-server-standalone-2.22.0.jar > /dev/null 2>&1 &
  - sleep 30  # to wait for Selenium to be up and running
  - cd tests/unit
  - phpunit --version  
  - phpenv rehash
script: 
  - phpunit --configuration phpunit.example.xml .
  - #java -jar ../../selenium-server-standalone-2.15.0.jar -htmlSuite "*firefox" "http://127.0.0.1:8080" "../selenium/testSuite.html" "../../Result.html"
  - #phpcs src
