language: php
php:
  - 5.3
before_script:
  - mysql -e 'create database IF NOT EXISTS intraface_test;'
  - pear install --force --alldeps pear_packagefilemanager
  - pear channel-discover pear.phing.info
  - pear channel-discover pear.pdepend.org
  - pear channel-discover pear.phpunit.de
  - pear channel-discover pearmd.org
  - pear channel-discover docblox-project.org
  - pear install phing/Phing
  - pear channel-discover pear.domain51.com
  - pear install --force pear.domain51/Phing_d51PearPkg2Task
  - pear channel-discover pear.saltybeagle.com
  - pear install --force --alldeps intrafacepublic/Phing_IlibPearDeployerTask 
  - pear install --force --alldeps pear/PHP_CodeSniffer 
  - pear channel-discover public.intraface.dk
  - pear channel-discover pear.doctrine-project.org
  - pear channel-discover htmlpurifier.org
  - pear channel-discover pear.michelf.com
  - pear channel-discover pearhub.org
  - php generate_package_xml.php make
  - pear package src/package.xml
  - sudo pear install --alldeps --force src/Intraface-X.Y.Z.tgz
  - sudo rm src/Intraface-X.Y.Z.tgz
  - phpenv rehash
script: phpunit --configuration tests/unit/phpunit.example.xml tests/unit/.
