sudo: false
language: php

php:
  - 5.3

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache

install:

  # Create database
  - mysql -e 'create database IF NOT EXISTS intraface_test;'

  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

  # Setup database for unit tests
  - php tests/unit/setup_database.php

  # Generating the selenium test suite file
  # - pear install phpunit/PHPUnit_Selenium
  # - pear install --force intrafacepublic/Ilib_Testing_Selenium_Selenese_TestSuiteGenerator-0.1.2
  # - php tests/selenium/generate_test_suite.php

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

  # Start simple HTTP-Server
  # - cd src/intraface.dk
  # - python -m SimpleHTTPServer 8080 > /dev/null 2>&1 &

before_script:
  #- cd ../../tests/unit
  #- phpunit --version
  #- phpenv rehash

script:
  - cd tests/unit/
  - ../../vendor/bin/phpunit --verbose --configuration phpunit.example.xml .
  - cd ../../
  # - java -jar senium-server-standalone-2.37.0.jar -htmlSuite "*firefox" "http://127.0.0.1:8080" "../selenium/testSuite.html" "testResults.html"
  - ./vendor/bin/phpcs --standard=phpcs.xml src/Intraface
  - ./vendor/bin/phpcs --standard=phpcs.xml tests/unit
